site_name: ChatFlow

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            show_submodules: false

nav:
  - ChatFlow: index.md
  - Quick Start: quick-start.md
  - Tutorial: tutorials.md
  - Grammar:
    - Structure: structure.md
    - Lexical Analysis: lexical.md
    - Statements : statement.md
    - Definition : BNF.md
  - API Reference: reference.md
  - License: LICENSE.md
